export enum PaymentScenario {
	SUCCESS = 'SUCCESS',
	INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
	CARD_EXPIRED = 'CARD_EXPIRED',
	DECLINED_BY_BANK = 'DECLINED_BY_BANK',
	GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT'
}
